baseURL = 'https://ntrop6.github.io/'
languageCode = 'tr'
title = 'silly website'
theme = 'PaperMod'

[params]
  defaultTheme = 'dark'

  [params.profileMode]
  enabled = true
  disableThemeToggle = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
