baseURL = 'https://ntrop6.github.io/'
languageCode = 'tr'
title = 'silly website'
theme = 'PaperMod'

[params]
  defaultTheme = 'dark'
  
  copyright = 'silly website | discord:ntrop6 | <a href="https://files.catbox.moe/uci9zc.gif" target="_blank">önemli</a>'

[params.profileMode]
  enabled = true
  title = "meraba"
  subtitle = "Projelerim,"
  imageUrl = "https://files.catbox.moe/dngyr0.jpg"
  imageTitle = "aynı ben"
  imageWidth = 150
  imageHeight = 150

  [[params.profileMode.buttons]]
  name = "Tsukihime Türkçe"
  url = "https://github.com/ntrop6"

  [[params.profileMode.buttons]]
  name = "Doujin Çevirileri"
  url = "https://github.com/ntrop6"

  [[params.profileMode.buttons]]
  name = "Resim/Animasyon"
  url = "https://github.com/ntrop6"

[menu]
  [[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search"
  weight = 10
